/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2026-03-23 18:36:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Rodado;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rodadoForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<form class=\"form-crear-rodado\" action=\"");
      out.print( request.getContextPath() );
      out.write("/crearRodado\" method=\"post\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Campo Patente (Texto) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"patente\">Patente</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"patente\" name=\"patente\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Chasis (Texto) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"chasis\">Número de Chasis</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"chasis\" name=\"chasis\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Color (Texto) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"color\">Color</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"color\" name=\"color\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Caja (Enum) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"caja\">Tipo de Caja</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"caja\" name=\"caja\">\r\n");
      out.write("            <option value=\"MANUAL\">Manual</option>\r\n");
      out.write("            <option value=\"AUTOMATICO\">Automática</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Motor (Enum) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"motor\">Motor</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"motor\" name=\"motor\">\r\n");
      out.write("            <option value=\"DIESEL\">diesel</option>\r\n");
      out.write("            <option value=\"HIBRIDO\">Híbrido</option>\r\n");
      out.write("            <option value=\"ELECTRICO\">Eléctrico</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Estado (Enum) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"TipoEstado\">Estado del Vehículo</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"TipoEstado\" name=\"TipoEstado\">\r\n");
      out.write("            <option value=\"NUEVO\">Nuevo</option>\r\n");
      out.write("            <option value=\"USADO\">Usado</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Consumo (Enum) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"TipoConsumo\">Tipo de Consumo</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"TipoConsumo\" name=\"TipoConsumo\">\r\n");
      out.write("            <option value=\"BAJO\">Bajo</option>\r\n");
      out.write("            <option value=\"MEDIO\">Medio</option>\r\n");
      out.write("            <option value=\"ALTO\">Alto</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Puertas (Enum) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"puertas\">Cantidad de Puertas</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"puertas\" name=\"puertas\">\r\n");
      out.write("            <option value=\"DOS\">2 Puertas</option>\r\n");
      out.write("            <option value=\"TRES\">3 Puertas</option>\r\n");
      out.write("            <option value=\"CUATRO\">4 Puertas</option>\r\n");
      out.write("            <option value=\"CINCO\">5 Puertas</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Campo Tipo de Rodado (Enum) -->\r\n");
      out.write("    <div class=\"form-group mb-3\">\r\n");
      out.write("        <label for=\"TipoRodado\">Categoría de Rodado</label>\r\n");
      out.write("        <select class=\"form-control\" id=\"TipoRodado\" name=\"TipoRodado\">\r\n");
      out.write("            <option value=\"AUTO\">Auto</option>\r\n");
      out.write("            <option value=\"CAMIONETA\">Camioneta</option>\r\n");
      out.write("            <option value=\"MOTO\">Moto</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary mt-3\">Guardar Rodado</button>\r\n");
      out.write("    ");
 if ("success".equals(request.getParameter("status"))) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-success\">¡Rodado guardado con éxito en la base de datos!</div>\r\n");
 } else if ("error".equals(request.getParameter("status"))) { 
      out.write("\r\n");
      out.write("    <div class=\"alert alert-danger\">Hubo un error al guardar. Revisa la consola.</div>\r\n");
 } 
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
